os:
  - linux

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - pecl channel-update pecl.php.net
  - yes "" | pecl install yaml
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - composer ci

matrix:
  allow_failures:
    - php: 7.4snapshot

notifications:
  email:
    on_success: never
    on_failure: always
